// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Price     pgtype.Numeric   `json:"price"`
	Quantity  int32            `json:"quantity"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
