// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	CreateOrder(ctx context.Context, customerID int32) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindProductByID(ctx context.Context, id int32) (Product, error)
	FindProductsByIDs(ctx context.Context, dollar_1 []int32) ([]FindProductsByIDsRow, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID int32) ([]GetOrderItemsByOrderIDRow, error)
	GetOrdersByCustomerID(ctx context.Context, customerID int32) ([]GetOrdersByCustomerIDRow, error)
	GetProducts(ctx context.Context) ([]Product, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
}

var _ Querier = (*Queries)(nil)
